# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python tests for napalm-oneaccess-oneos

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
          python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        export PATH="$PATH:$HOME/.local/bin"
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements-dev.txt
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        export PATH="$PATH:$HOME/.local/bin"
        pytest
